# Hello HL people. This should *ONLY* be used with Vagrant deployments and testing.
---
  - hosts: all
    become: yes
    tasks:

      # Install vim to keep sanity
      - name: Install vim
        yum: name=vim state=present

      # Start influxDB install
      - name: Add InfluxDB repo
        copy: src=influxdb.repo dest=/etc/yum.repos.d/influxdb.repo owner=root group=root mode=0644

      - name: Install required packages for influxdb tic tac
        yum: name={{ item }} enablerepo=influxdb state=present
        with_items:
          - influxdb
          - kapacitor
          - telegraf

      - name: Download and install chronograf
        yum: name=https://dl.influxdata.com/chronograf/releases/chronograf-1.1.0~beta4.x86_64.rpm state=present

      - name: Start influx db tic tac
        service: name={{ item }} state=started
        with_items:
          - influxdb
          - telegraf
          - kapacitor
          - chronograf

      # - name: start InfluxDB
      #   service: name=influxdb state=started
      #
      # - name: start telegraf
      #   service: name=telegraf state=started
      #
      # - name: start chronograf
      #   service: name=chronograf state=started
      #
      # - name: start kapacitor
      #   service: name=kapacitor state=started

      - name: Enable influx and all deps to start on reboot
        shell: systemctl enable influxdb kapacitor telegraf chronograf
